job_id: LMRt_quickstart
job_dirpath: ./recon

recon_period: [0, 2000]
recon_timescale: 1
recon_nens: 100
recon_seeds: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
recon_vars: tas
# recon_vars: [tas, pr]  # reconstruct two fields at once
recon_loc_rad: 25000  # unit: km


# Proxy & PSM related
proxydb_path: ./data/proxy/pages2k_dataset.pkl

ptype_psm:  # assimilate only listed proxy types
  # tree.TRW: bilinear
  # tree.MXD: linear
  coral.d18O: linear
  coral.SrCa: linear
  coral.calc: linear

ptype_season:  # one may list all possible proxy types here
  # tree.TRW: [[1,2,3,4,5,6,7,8,9,10,11,12],[6,7,8],[3,4,5,6,7,8],[6,7,8,9,10,11],[-12,1,2],[-9,-10,-11,-12,1,2],[-12,1,2,3,4,5]]  # multiple possible seasonalities
  # tree.MXD: [[1,2,3,4,5,6,7,8,9,10,11,12],[6,7,8],[3,4,5,6,7,8],[6,7,8,9,10,11],[-12,1,2],[-9,-10,-11,-12,1,2],[-12,1,2,3,4,5]]
  coral.d18O: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]  # annual
  coral.SrCa: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]  # annual
  coral.calc: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]  # annual

psm_calib_period: [1850, 2015]
proxy_frac: 0.75  # assimilated fraction of the proxy records

# Prior related
anom_period: [1951, 1980]

prior_path:
  tas: ./data/prior/b.e11.BLMTRC5CN.f19_g16.001.cam.h0.TREFHT.085001-184912.nc
  # pr: ./data/prior/b.e11.BLMTRC5CN.f19_g16.001.cam.h0.PRECT.085001-184912.nc
  # psl: ./data/prior/b.e11.BLMTRC5CN.f19_g16.001.cam.h0.PSL.085001-184912.nc

prior_varname:
  tas: TREFHT
  # pr: PRECT
  # psl: PSL

prior_regrid_ntrunc: 42

prior_season: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]  # annual

# Instrumental observations related
obs_path:
  tas: ./data/obs/gistemp1200_ERSSTv4.nc
  # pr: ./data/obs/GPCC_precip.mon.flux.1x1.v6.nc

obs_varname:
  tas: tempanomaly
  # pr: precip