source "https://rubygems.org"

# to publish on github page
gem 'github-pages', group: :jekyll_plugins


group :jekyll_plugins do
  gem "webrick" # needed for Ruby v3
end

# to publich without github page
#gem "jekyll"
