name: Deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Check repository
        uses: actions/checkout@v2

      - name: Setup Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: 3.x

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true

      - name: Install dependencies
        run: pip install click requests docker

      - name: Create a Dockerfile for the test model
        working-directory: ./tests/
        run: python3 ../controller/packageScript.py create --run python ./bogus_python_model.py

      - name: Build the test climate model
        working-directory: ./tests/
        run: python3 ../controller/packageScript.py build ci/test-model

      - name: Run the test climate model
        working-directory: ./tests/
        run: python3 ../controller/packageScript.py run ci/test-model
